version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: miastodos_postgres
    environment:
      POSTGRES_DB: maistodos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: maistodos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
