version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: maistodos_postgres
    environment:
      POSTGRES_DB: maistodos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: maistodos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    command: bash -c "python manage.py makemigrations cards && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/maistodos

volumes:
  pgdata:
