# Generated by Django 4.2.4 on 2023-08-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='flag',
            field=models.CharField(choices=[('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('Elo', 'Elo'), ('Dinners Club', 'Dinners Club'), ('American Express', 'American Express')], default=2, max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], default=1, max_length=20),
        ),
    ]
