# Generated by Django 4.2.4 on 2023-08-23 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('exp_date', models.DateField()),
                ('holder', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=16)),
                ('cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
